### ISSUE TITLE
Minor details- TODO

### ISSUE THREAD

**Issue by LLxD** [ArticaDev/fatima-imoveis#3]
- [x]  Colocar o valor no final do card

- [x]  Adicionar um botão no card para dar display no valor

- [x]  Melhorar a colorização

- [x]  Remover text-decoration

- [x]  Testar estilizações no card

- [x]  Alterar fotos de sample

- [x]  Editar fontes e paddings

- [x]  Decidir colorização dos elementos do card

- [x]  Procurar um novo logo pra olx

- [x]  Formatar o valor min e máx para currency
